site_name: Datávoros 
site_url: https://socialtic.github.io/datavoros
site_description: Documentación del proyecto "Datávoros"

nav:
  - Home: 'index.md'
  - Tutoriales para analizar una app:
      - 'Instalación del laboratorio de análisis': '01-instalacion-laboratorio.md'
      - 'Captura y análisis de tráfico de red': '02-captura-trafico-analisis.md'
      - 'Mapeo de permisos y rastreadores': '03-permisos y trackers.md'
      - 'Cómo bajar un archivo APK para analizarlo': '04-apk-download.md'
      - 'Cómo instalar y utilizar MobSF': '05-instalacion-y-uso-de-mobfs.md'
  - Plantila de aplicación: '00-plantilla-reporte.md'
  - Aplicaciones analizadas:
    - Aplicaciones de seguridad:

        - 9 1 1 Emergencias: '01-apps-de-seguridad/9-1-1Emergencias/911emergencias.md'
        - 911CDMX: '01-apps-de-seguridad/911CDMX/911cdmx.md'
        - 911 MóvilBC: '01-apps-de-seguridad/911MovilBC/911movilbc.md'
        - Botón de Auxilio Jalisco: '01-apps-de-seguridad/boton_auxilio_jalisco/boton-de-auxilio-jalisco.md'
        -  Mi Policía: '01-apps-de-seguridad/mi-policia/mi-policia.md'
        - Mujeres Seguras: '01-apps-de-seguridad/mujeres-seguras/mujeres-seguras.md'
        - Seguridad Incluyente ahora Escudo Puebla: '01-apps-de-seguridad/seguridad-incluyente-escudo-puebla/seguridad-incluyente-escudo-puebla.md'
   # - Aplicaciones de Video:
       # - B612: 'aaa'   
       # - Canvas: 'bbb'
       # - Sticker.ly: 'ccc'
       # - Picsart: 'ddd'
       # - Sweet Selfie Camera Editor: 'eee'
   # - Aplicaciones de Montadeudas:
       # - Cashbox: 'aaa'
       # - Creditolana: 'bbb'
       # - iFectivo: 'ccc'
       # - Okredito: 'ddd'
       # - Superapoyo: 'eee'
       # - Tala: 'fff'

  - Listado de rastreadores y permisos:
      - 'Permisos': '99-listado-permisos.md'
      - 'Trackers': '99-listado-trackers.md'
  - Contribuye: 'contribuye.md'

theme:
  name: material
  language: es
  logo: img/icono.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
plugins:
  - search:
      separator: '[\s\-\.\_]'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/qttd
    - icon: material/web
      link: https://socialtic.org

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
