site_name: Datávoros
site_url: https://socialtic.github.io/datavoros
site_description: Documentación del proyecto "Datávoros"

nav:
  - Home: 'index.md'
  - Tutoriales para analizar una app:
    - Inicio: 'tutoriales/inicio.md'  
    - Instalación del laboratorio de análisis: 'tutoriales/01-instalacion-laboratorio.md'
    - Captura y análisis de tráfico de red: 'tutoriales/02-captura-trafico-analisis.md'
    - Mapeo de permisos y rastreadores: 'tutoriales/03-permisos y trackers.md'
    - Cómo bajar un archivo APK para analizarlo: 'tutoriales/04-apk-download.md'
    - Cómo instalar y utilizar MobSF: 'tutoriales/05-instalacion-y-uso-de-mobfs.md'
  - Plantilla de aplicación: 'plantilla-reporte.md'
  - Aplicaciones analizadas: 
    - Inicio: 'aplicaciones.md'
    - Aplicaciones de seguridad:
      - 9 1 1 Emergencias: '01-apps-de-seguridad/9-1-1Emergencias/911emergencias.md'
      - 911CDMX: '01-apps-de-seguridad/911CDMX/911cdmx.md'
      - 911 MóvilBC: '01-apps-de-seguridad/911MovilBC/911movilbc.md'
      - Botón de Auxilio Jalisco: '01-apps-de-seguridad/boton-auxilio-jalisco/boton-de-auxilio-jalisco.md'
      - Mi Policía: '01-apps-de-seguridad/mi-policia/mi-policia.md'
      - Mujeres Seguras: '01-apps-de-seguridad/mujeres-seguras/mujeres-seguras.md'
      - Seguridad Incluyente ahora Escudo Puebla: '01-apps-de-seguridad/seguridad-incluyente-escudo-puebla/seguridad-incluyente-escudo-puebla.md'
      - Veracruz Mujer Alerta: '01-apps-de-seguridad/mujer-alerta-veracruz/mujer-alerta-veracruz.md'
    - Aplicaciones de Video:
       - B612: '02-apps-de-video-y-foto/b612/B612.md'   
       - Canva: '02-apps-de-video-y-foto/canva/canva.md'
       - Sticker.ly: '02-apps-de-video-y-foto/stickerly/stickerly.md'
       - Picsart: '02-apps-de-video-y-foto/picsart/picsart.md'
       - Sweet Selfie Camera Editor: '02-apps-de-video-y-foto/sweetselfie-camera-editor/sweetselfie.md'
    - Aplicaciones de Montadeudas:
       - Creditolana: '03-apps-de-montadeudas/creditolana/creditolana.md'
       - iFectivo: '03-apps-de-montadeudas/ifectivo/ifectivo.md'
       - Okredito: '03-apps-de-montadeudas/okredito/okredito.md'
       - Superapoyo: '03-apps-de-montadeudas/superapoyo/superapoyo.md'
       - Tala: '03-apps-de-montadeudas/tala/tala.md'

  - Listado de rastreadores y permisos:
    - Inicio: 'trackers-permisos/inicio.md'
    - Permisos: 'trackers-permisos/99-listado-permisos.md'
    - Rastreadores: 'trackers-permisos/99-listado-trackers.md'
  - Contribuye: 'contribuye.md'

theme:
  name: material
  language: es
  logo: img/icono.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
plugins:
  - search:
      separator: '[\s\-\.\_]'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/qttd
    - icon: material/web
      link: https://socialtic.org

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
